"use client"
import React, { useState, useEffect } from 'react';

// Define the type for the report structure, now including UPID and remarks
interface Report {
  id: number;
  category: string;
  title: string;
  content: string;
  upid: string; // Unique Patient ID
  dateGenerated: string; // Date when the report was generated (string)
  remarks: string; // Remarks by the person who generated the report
}

const reports: Report[] = [
  { 
    id: 1, 
    category: 'Asthma', 
    title: 'Asthma Report 1', 
    content: 'Details of report 1',
    upid: 'P001', 
    dateGenerated: '2024-12-23', 
    remarks: 'Report generated by Dr. Smith'
  },
  { 
    id: 2, 
    category: 'Asthma', 
    title: 'Asthma Report 2', 
    content: 'Details of report 2',
    upid: 'P002', 
    dateGenerated: '2024-12-21', 
    remarks: 'Report generated by Dr. Johnson'
  },
  { 
    id: 3, 
    category: 'Asthma', 
    title: 'Asthma Report 3', 
    content: 'Details of report 3',
    upid: 'P003', 
    dateGenerated: '2024-12-22', 
    remarks: 'Report generated by Dr. Davis'
  },
  { 
    id: 4, 
    category: 'Asthma', 
    title: 'Asthma Report 4', 
    content: 'Details of report 4',
    upid: 'P001', 
    dateGenerated: '2024-12-23', 
    remarks: 'Report generated by Dr. Smith'
  },
];

// Sort reports by the latest date first
const sortReportsByDate = (reports: Report[]) => {
  return reports.sort((a, b) => (new Date(b.dateGenerated).getTime() - new Date(a.dateGenerated).getTime()));
};

export default function AsthmaReportsPage() {
  // State to hold filtered reports by category "Asthma"
  const [filteredReports, setFilteredReports] = useState<Report[]>([]);
  const [selectedDate, setSelectedDate] = useState<string>('');

  useEffect(() => {
    // Filter reports by category "Asthma" and sort them by latest date
    const asthmaReports = reports.filter(report => report.category === 'Asthma');
    const sortedReports = sortReportsByDate(asthmaReports);
    setFilteredReports(sortedReports);
  }, []);

  // Filter reports by selected date
  const handleDateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const date = event.target.value;
    setSelectedDate(date);

    if (date) {
      // Filter reports for the selected date
      const reportsByDate = reports.filter(report => report.dateGenerated === date && report.category === 'Asthma');
      setFilteredReports(sortReportsByDate(reportsByDate)); // Sort by date in descending order
    } else {
      // If no date is selected, show all reports
      const asthmaReports = reports.filter(report => report.category === 'Asthma');
      setFilteredReports(sortReportsByDate(asthmaReports)); // Sort by date in descending order
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-r from-blue-50 to-blue-100 flex items-center justify-center px-4">
      <div className="max-w-4xl w-full bg-white shadow-lg rounded-lg p-8">
        <h1 className="text-3xl font-extrabold text-gray-800 text-center mb-6">Asthma Reports</h1>

        {/* Date Picker to Filter Reports */}
        <div className="mb-6">
          <label className="text-sm font-semibold text-gray-600 mb-2">Filter by Date</label>
          <input 
            type="date" 
            value={selectedDate} 
            onChange={handleDateChange} 
            className="w-full border border-gray-300 px-4 py-2 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
        </div>

        {filteredReports.length > 0 ? (
          <div className="space-y-6">
            {filteredReports.map(report => (
              <div key={report.id} className="border p-4 rounded-lg shadow-md">
                <h2 className="text-xl font-semibold text-gray-800">{report.title}</h2>
                <p className="text-gray-600">{report.content}</p>
                <div className="mt-4 text-sm text-gray-500">
                  <p><strong>Patient ID (UPID):</strong> {report.upid}</p>
                  <p><strong>Date Generated:</strong> {report.dateGenerated}</p>
                  <p><strong>Remarks:</strong> {report.remarks}</p>
                </div>
                <div className="mt-4 text-center">
                  <button 
                    onClick={() => alert(`Viewing report for UPID: ${report.upid}`)} 
                    className="px-6 py-2 bg-gradient-to-r from-blue-500 to-blue-600 text-white font-semibold rounded-lg shadow-lg hover:from-blue-600 hover:to-blue-700 transition duration-300"
                  >
                    View Report
                  </button>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-center text-lg text-gray-600">No asthma reports available.</p>
        )}
      </div>
    </div>
  );
}
